services:
  - type: web
    name: AulaKitPro
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r AulaKitPro_Web/requirements.txt
      python AulaKitPro_Web/manage.py collectstatic --no-input
      python AulaKitPro_Web/manage.py migrate
    startCommand: gunicorn AulaKitPro_Core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///aulakitpro.sqlite3"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    disks:
      - name: sqlite-data
        mountPath: /var/data
        sizeGB: 1
