# Blueprint para desplegar AulaKitPro en Render
services:
  - name: AulaKitPro
    type: web
    env: python
    rootDir: AulaKitPro_Web
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --no-input"
    startCommand: "gunicorn AulaKitPro_Core.wsgi"
    disks:
      - name: sqlite-data
        mountPath: /app/sqlite
        sizeGB: 1
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        fromService:
          type: web
          name: AulaKitPro
          property: host
